spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///caro2o?serverTimezone=UTC
      username: root
      password: 123456
mybatis-plus:
  mapper-locations: classpath:cn/wolfcode/caro2o/mapper/*Mapper.xml
